import Link from "next/link";

export const metadata = {
  title: "Terms of Service | AuditTrail.dev",
  description: "Terms of Service for AuditTrail.dev",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-100 py-4 px-6">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="text-lg font-semibold text-gray-900">
            AuditTrail<span className="text-accent">.dev</span>
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-semibold text-gray-900 mb-8">Terms of Service</h1>

        <div className="prose prose-gray max-w-none text-sm text-gray-600 space-y-6">
          <p className="text-gray-500">Last updated: January 2025</p>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using AuditTrail.dev (&quot;Service&quot;), you accept and agree to
              be bound by these Terms of Service. If you do not agree to these terms, please do not
              use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">
              2. Description of Service
            </h2>
            <p>
              AuditTrail.dev provides compliance evidence generation from GitHub repository data. We
              collect metadata including commit information, pull request details, code reviews, and
              branch protection settings to map against compliance frameworks.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">3. GitHub Integration</h2>
            <p>
              Our Service requires read-only access to your GitHub repositories. We do not modify,
              delete, or write any data to your repositories. You can revoke access at any time
              through your GitHub settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">4. Data Collection</h2>
            <p>We collect and store the following metadata from your repositories:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Commit hashes, messages, authors, and timestamps</li>
              <li>Pull request numbers, titles, authors, and merge status</li>
              <li>Code review information (reviewer, approval status)</li>
              <li>Branch protection rule configurations</li>
            </ul>
            <p className="mt-2">We do not store your source code or file contents.</p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">
              5. Subscription and Payments
            </h2>
            <p>
              Paid subscriptions are billed monthly through Stripe. You may cancel at any time, and
              your subscription will remain active until the end of the current billing period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">6. Compliance Reports</h2>
            <p>
              Reports generated by AuditTrail.dev are provided for informational purposes. While we
              map GitHub activity to compliance controls, the reports do not constitute legal or
              compliance advice. You are responsible for verifying the accuracy of reports with
              qualified professionals.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">
              7. Limitation of Liability
            </h2>
            <p>
              AuditTrail.dev is provided &quot;as is&quot; without warranties of any kind. We are
              not liable for any damages arising from the use of our Service, including but not
              limited to audit failures or compliance issues.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">8. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. We will notify users of significant
              changes via email or through the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-medium text-gray-900 mt-8 mb-4">9. Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href="mailto:legal@audittrail.dev" className="text-gray-900 hover:underline">
                legal@audittrail.dev
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-100">
          <Link href="/" className="text-sm text-gray-500 hover:text-gray-900">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
